name: buteo-dev
channels:
  - defaults
dependencies:
  - _libgcc_mutex=0.1=main
  - _openmp_mutex=5.1=1_gnu
  - attrs=22.1.0=py310h06a4308_0
  - blas=1.0=mkl
  - blosc=1.21.3=h6a678d5_0
  - boost-cpp=1.73.0=h7f8727e_12
  - bzip2=1.0.8=h7b6447c_0
  - c-ares=1.19.0=h5eee18b_0
  - ca-certificates=2023.01.10=h06a4308_0
  - cairo=1.16.0=hb05425b_4
  - cfitsio=3.470=h5893167_7
  - curl=7.88.1=h5eee18b_0
  - exceptiongroup=1.0.4=py310h06a4308_0
  - expat=2.4.9=h6a678d5_0
  - fontconfig=2.14.1=h4c34cd2_2
  - freetype=2.12.1=h4a9f257_0
  - freexl=1.0.6=h27cfd23_0
  - gdal=3.6.2=py310h65ec567_1
  - geos=3.8.0=he6710b0_0
  - geotiff=1.7.0=h2a26cda_1
  - giflib=5.2.1=h5eee18b_3
  - glib=2.69.1=he621ea3_2
  - hdf4=4.2.13=h3ca952b_2
  - hdf5=1.10.6=h3ffc7dd_1
  - icu=58.2=he6710b0_3
  - iniconfig=1.1.1=pyhd3eb1b0_0
  - intel-openmp=2023.1.0=hdb19cb5_46305
  - jpeg=9e=h5eee18b_1
  - json-c=0.16=h5eee18b_0
  - kealib=1.5.0=hd940352_0
  - krb5=1.19.4=h568e23c_0
  - lcms2=2.12=h3be6417_0
  - ld_impl_linux-64=2.38=h1181459_1
  - lerc=3.0=h295c915_0
  - libboost=1.73.0=h28710b8_12
  - libcurl=7.88.1=h91b91d3_0
  - libdeflate=1.17=h5eee18b_0
  - libedit=3.1.20221030=h5eee18b_0
  - libev=4.33=h7f8727e_1
  - libffi=3.4.4=h6a678d5_0
  - libgcc-ng=11.2.0=h1234567_1
  - libgdal=3.6.2=hc0e11bb_1
  - libgfortran-ng=11.2.0=h00389a5_1
  - libgfortran5=11.2.0=h1234567_1
  - libgomp=11.2.0=h1234567_1
  - libiconv=1.16=h7f8727e_2
  - libkml=1.3.0=h096b73e_6
  - libllvm14=14.0.6=hdb19cb5_3
  - libnetcdf=4.8.1=h8322cc2_2
  - libnghttp2=1.46.0=hce63b2e_0
  - libpng=1.6.39=h5eee18b_0
  - libpq=12.9=h16c4e8d_3
  - libspatialite=4.3.0a=h21ec0d7_23
  - libssh2=1.10.0=h8f2d780_0
  - libstdcxx-ng=11.2.0=h1234567_1
  - libtiff=4.5.0=h6a678d5_2
  - libuuid=1.41.5=h5eee18b_0
  - libwebp-base=1.2.4=h5eee18b_1
  - libxcb=1.15=h7f8727e_0
  - libxml2=2.10.3=hcbfbd50_0
  - libzip=1.8.0=h5cef20c_0
  - llvmlite=0.40.0=py310he621ea3_0
  - lz4-c=1.9.4=h6a678d5_0
  - mkl=2023.1.0=h6d00ec8_46342
  - mkl-service=2.4.0=py310h5eee18b_1
  - mkl_fft=1.3.6=py310h1128e8f_1
  - mkl_random=1.2.2=py310h1128e8f_1
  - ncurses=6.4=h6a678d5_0
  - nspr=4.35=h6a678d5_0
  - nss=3.89.1=h6a678d5_0
  - numba=0.57.0=py310h1128e8f_0
  - numpy=1.24.3=py310h5f9d8c6_1
  - numpy-base=1.24.3=py310hb5e798b_1
  - openjpeg=2.4.0=h3ad879b_0
  - openssl=1.1.1t=h7f8727e_0
  - packaging=23.0=py310h06a4308_0
  - pcre=8.45=h295c915_0
  - pcre2=10.37=he7ceb23_1
  - pip=23.0.1=py310h06a4308_0
  - pixman=0.40.0=h7f8727e_1
  - pluggy=1.0.0=py310h06a4308_1
  - poppler=22.12.0=h381b16e_0
  - poppler-data=0.4.11=h06a4308_1
  - postgresql=12.9=h16c4e8d_3
  - proj=6.2.1=h05a3930_0
  - psutil=5.9.0=py310h5eee18b_0
  - pytest=7.3.1=py310h06a4308_0
  - python=3.10.11=h7a1cb2a_2
  - qhull=2020.2=hdb19cb5_2
  - readline=8.2=h5eee18b_0
  - setuptools=67.8.0=py310h06a4308_0
  - sqlite=3.41.2=h5eee18b_0
  - tbb=2021.8.0=hdb19cb5_0
  - tiledb=2.3.3=h1132f93_2
  - tk=8.6.12=h1ccaba5_0
  - tomli=2.0.1=py310h06a4308_0
  - tzdata=2023c=h04d1e81_0
  - wheel=0.38.4=py310h06a4308_0
  - xerces-c=3.2.4=h94c2ce2_0
  - xz=5.4.2=h5eee18b_0
  - yaml=0.2.5=h7b6447c_0
  - zlib=1.2.13=h5eee18b_0
  - zstd=1.5.5=hc292b87_0
prefix: /root/anaconda3/envs/buteo-dev
